### ISSUE TITLE
Create Funnels/Functional storage interaction not always working

### ISSUE THREAD

**Issue by Sunekaer** [Buuz135/FunctionalStorage#10]
Bug Description
Sometimes the funnel on a 1x2 drawer stops working and wont pick up one of the 2 items
Steps to reproduce
make 1x2 drawer
put different items in
put funnel on
sometimes it works, sometimes it stops working
Expected behaviour
It picking up the items
Screenshots
![image](https://user-images.githubusercontent.com/18720460/149626218-04178c48-3a82-4a55-bcac-79f2c1490008.png)
Additional info
Didnt get the bug with normal chest.
Somehow, item stacks with exact same id, and nbt (even no nbt) can not merge.

Not fully sure if this is Create or FS issue

**Comment by Buuz135** [comment]
I can get it happen with a normal chest. It doesn't even try to insert it.
![NVIDIA_Share_ESqbuzSeHF](https://user-images.githubusercontent.com/3874674/149629493-b2d4adf7-4331-4c2c-a613-0e96d634e802.png)

Placing a funnel on the top side of a block works perfectly with a drawer or a chest but on the bottom side it has a very 
 inconsistent beheviour. For it to work 100% on the bottom side the item needs to have a motion going up.

https://user-images.githubusercontent.com/3874674/149629785-3c08c5b7-277d-4b05-a652-7d73d2b8f1c7.mp4

**Comment by Naxanria** [comment]
The funnel only takes from block it is in, so the halfslab underneath is outside the radius

**Comment by Buuz135** [comment]
https://user-images.githubusercontent.com/3874674/149630304-aa6f54ac-6db6-43f5-bfee-44cfa350c5dd.mp4


https://user-images.githubusercontent.com/3874674/149630354-a5b5c4cb-b668-4f51-bf54-681b77375fd3.mp4

**Comment by Buuz135** [comment]
With a funnel on top it doesnt happen

https://user-images.githubusercontent.com/3874674/149630568-007c6b75-5f0a-4967-bb36-f4a86cbd8094.mp4

**Comment by andrewsf** [comment]
Seems like the videos in this ticket don't relate to the bug report at all?
The original screenshot shows a case that should work. An upward funnel below an inventory is sharing a block with items. All other screenshots and videos do not show this case. They show other totally expected behaviors.
