### ISSUE TITLE
Productive Bees Mod's added honey combs not all rending in drawers

### ISSUE THREAD

**Issue by rennsport** [Buuz135/FunctionalStorage#101]
Productive bees adds over 100 new honey combs to the game and not all of them are rendering (some are though). See attached screenshot. Two examples of combs not rendering are redstone comb and lapis comb.

Versions:
- Productive Bees: 1.18.2-0.9.1.5
- Functional Storage: 1.18.2-1.0.6
- Minecraft: 1.18.2
- Forge: 40.1.80

Additional notes:
- Using AllTheMods7 modpack

![Screen Shot 2022-10-06 at 10 45 35 AM](https://user-images.githubusercontent.com/982325/194383200-fd1ff270-564c-4982-b5de-a549bca269be.png)

**Comment by Buuz135** [comment]
Looking at the PB item models it seems that they are using block models for just an item and not a block? I think it on their side

**Comment by JaisDK** [comment]
Where do you determine that they are using a block model? They use a custom model loader which makes an `ItemMultiLayerBakedModel`
Is there something I could do different in the loader for it to work in the drawers?

https://github.com/JDKDigital/productive-bees/blob/dev-1.18.2/src/main/resources/assets/productivebees/models/item/honeycomb_base.json

https://github.com/JDKDigital/productive-bees/blob/dev-1.18.2/src/main/java/cy/jdkdigital/productivebees/client/model/CombModel.java

**Comment by JaisDK** [comment]
There's also an issue displaying some ChemLib items
https://github.com/SmashingMods/ChemLib/blob/1.18.x/src/generated/resources/assets/chemlib/models/item/yttrium.json

**Comment by Buuz135** [comment]
Reopening to check it out later

**Comment by Buuz135** [comment]
Might be fixed in https://github.com/Buuz135/FunctionalStorage/pull/137
Backport soon
