### ISSUE TITLE
[Request] make already filled drawers priority when piping into drawer controller

### ISSUE THREAD

**Issue by bloodtap** [Buuz135/FunctionalStorage#103]
Suggestion: make already filled drawers priority when piping into drawer controller

at the moment if I pipe Items (even from vanilla hoppers) into a drawer controller with unlocked drawers it will place the items at random drawers, (IE if I'm exporting gold into a drawer controller the controller will put them into a random spot, then when it gets more gold rather then pumping it into the already partially filled gold drawer it pumps it into another drawer.)

This means that having unlocked overflow drawers at the end of a line, (incase of items you didn't account for), is impossible

**Comment by KellAtreides** [comment]
Yes.  Especially for a mob farm when extra items like heads can drop.

**Comment by shikyo13** [comment]
This is what I came here for. Please prioritize (hehe pun) prioritization! ♥ . This mod is amazing so far!

**Comment by FleX246** [comment]
I love this Mod in Stoneblocks 3 !!!

I find the direct display of the content as a number much better than the red bar in StorageDrawers.
Personally, I like the upgrade options better here.

But the fact that drawers that are already filled are not prioritized when piping into the controller has prompted me to remove FunctionalStorage and play with StorageDrawers.

**Comment by AlexGuignard** [comment]
> I love this Mod in Stoneblocks 3 !!!
> 
> I find the direct display of the content as a number much better than the red bar in StorageDrawers. Personally, I like the upgrade options better here.
> 
> But the fact that drawers that are already filled are not prioritized when piping into the controller has prompted me to remove FunctionalStorage and play with StorageDrawers.

you can have the number int storage drawers too just use a quantity key instead of individual upgrades
this problem with functional drawers renders them kinda unusable imo

**Comment by FleX246** [comment]
> > I love this Mod in Stoneblocks 3 !!!
> > I find the direct display of the content as a number much better than the red bar in StorageDrawers. Personally, I like the upgrade options better here.
> > But the fact that drawers that are already filled are not prioritized when piping into the controller has prompted me to remove FunctionalStorage and play with StorageDrawers.
> 
> you can have the number with storage drawers too just use a quantity key instead of individual upgrades this problem with functional drawers renders them kinda unusable IMO That and the fucked lighting

Nice, thank you !
I have never seen this key

**Comment by Dustybonss** [comment]
Well since my thread was closed i hope Buuz is making this a reality.

**Comment by funAlways** [comment]
Hello, this is still an issue I believe. The commit above didn't solve this issue, the commit made the behavior to be "prioritize closest drawers", not "prioritize filled drawers before empty drawers". Drawer controllers currently still just puts the input item in the first valid slot regardless if there's other drawers with the item already or not.
