### ISSUE TITLE
Drawer justs deletes items instead of storing them

### ISSUE THREAD

**Issue by Porcy** [Buuz135/FunctionalStorage#104]
I have a golden furnace, from the mod Iron Furnaces. It ejects ingots into a drawer controller linked to 3 drawers above it. Controller accepts ingots and voids them instead of adding them into correct drawers. Had the same issue with a powered furnace from FTB Industrial Contraptions.
![2022-10-10_09 11 55](https://user-images.githubusercontent.com/8096340/194875014-0c2ccb0c-477b-4aa4-831e-7bf8a537ba0e.png)
![2022-10-10_09 11 37](https://user-images.githubusercontent.com/8096340/194875025-f8fbd04f-2f76-4f4f-ac41-4de19e58ad23.png)

**Comment by Buuz135** [comment]
Which mod version are you using

**Comment by Porcy** [comment]
1.18.2-1.0.6
Also, prior to locking the top drawer, the controller stuffed each empty slot with 64 iron ingots and then stopped filling them.

**Comment by Buuz135** [comment]
I think the furnaces are checking if the slot has 64 items and doing strange stuff, they shouldn't be doing that as the drawers can hold more than 64 items per slot
