### ISSUE TITLE
[1.19] Collecting upgrade not working

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#107]
According to the mod page, the upgrade should collect items in the ground, but nothing happens once I add it to the drawer.
Also, why does the upgrade have directions if it is supposed to collect all compatible items near it? 
![image](https://user-images.githubusercontent.com/44974827/197113665-af47743f-b980-48df-93d2-2b26ef57c821.png)

**Comment by Buuz135** [comment]
The drawer will collect items that are on the side specified in the direction, 1 block away, like a hopper

**Comment by ffuentesm** [comment]
Oh, could you add an option to have (all) sides as an option? And also maybe upgrade versions of it that increase the distance?
