### ISSUE TITLE
Linked Controllers Disappear

### ISSUE THREAD

**Issue by SpeedSlider** [Buuz135/FunctionalStorage#108]
Players on our Direwolf20 !.18 modpack have found that trying to move a linked controller will destroy the controller. Additionally, I did some testing, if you place a new controller in the same location, it will remember some of the drawer connections and will also disappear when trying to move it. You can clear the remember connections by placing a solid block in the previous controller's location.  The controller was connected to Refined Storage external storage controller and a LaserIO node. However, I tested a new controller not connected to the RS or LaserIO node and had the same problem. I am not sure if the problem still exists if you unlink the controller since I not sure how to unlink them.

**Comment by Buuz135** [comment]
What tool are you using to break it?

**Comment by SpeedSlider** [comment]
In my test I used a cobalt tinker's pickaxe and a vanilla iron one. It should be noted that both worked on an unlinked controller it was only after the controller was linked that when breaking it with either pick destroyed the controller.

**Comment by SpeedSlider** [comment]
We are playing FTB Direwolf20 1.18 pack (latest version, 1.9.1) which uses functionalstorage-1.18.2-0.0.14. I had done a search on your Github and FTB Github and did not find a similar open or closed issue. It should be noted that I am a server Admin for our streamer's community server so updating a single mod to see if it fixed the issue wasn't really an option since it would require all players to update the mod in their instance which is more difficult using the FTB launcher.

**Comment by Buuz135** [comment]
That is a very old version, try updating the mod
