### ISSUE TITLE
framed draw crash

### ISSUE THREAD

**Issue by Sunekaer** [Buuz135/FunctionalStorage#109]
_i made a framed draw from functional storage changed texture didnt like it so tried to change the same texture in the tinkers crafting station, game crashed on placing final item reloaded opened crafting station with same items already in crashed again 
Did more testing it seems to crash when trying to use slime as one of the decoration blocks
In any crafting table_

Crashlog: https://pastebin.com/69CPSLL3
Version: functionalstorage-1.18.2-1.0.7.jar

**Comment by klugemonkey** [comment]
Got similar issue when using a cobblestone chest on a crafting station...

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122421_()" because "side" is null
	at com.buuz135.functionalstorage.client.loader.FramedModel$Baked.getMinMaxPosition(FramedModel.java:228) 
...

It doesn't like some items textures and then crashes.

**Comment by duckslayr** [comment]
I got a crash when trying to use sand and a cactus for a framed drawer.

**Comment by Buuz135** [comment]
Should be fixed in https://github.com/Buuz135/FunctionalStorage/pull/127
Backport soon
