### ISSUE TITLE
Drawers broken and replaced with contents add a NBT tag to extracted items

### ISSUE THREAD

**Issue by MongoTheElder** [Buuz135/FunctionalStorage#11]
I was relocating some drawers that had items in them and noticed that I could no longer add additional items of the same type. Looking at the difference between items picked up out of the world and the same item pulled from a relocated drawer, there is an extra NBT tag on the items from the drawers that seem to be blocking them from matching in a stack. Drawers that have not been relocated work correctly (extracted items do not have an extra NBT tag)

Item from world:
![2022-01-15_10 23 33](https://user-images.githubusercontent.com/29290246/149627238-ca8d0a40-a07e-4690-ab08-c3a1996bee77.png)

Item from drawer:
![2022-01-15_10 23 35](https://user-images.githubusercontent.com/29290246/149627250-17342a45-d19c-4402-953f-eed6f220f532.png)

Functional Storage 1.18.1-0.0.7
Minecraft 1.18.1
Forge 39.0.9
Modpack: Team Rustic 4 (curseforge)

**Comment by Buuz135** [comment]
Would it be possible to get the nbt of that Cobblestone and the nbt of the drawer when picked up? I think you can run /kubejs hand or /kube hand

**Comment by MongoTheElder** [comment]
/kubejs hand (from drawer)
Item.of('minecraft:cobblestone', '{Charged:0b}')
'#engineersdecor:accepted_mineral_smelter_input'
'#forge:cobblestone'
'#minecraft:stone_crafting_materials'
'#minecraft:stone_tool_materials'
'#quark:stone_tool_materials'
'@minecraft'
'%building_blocks'

/kubejs hand (from world)
'minecraft:cobblestone'
'#engineersdecor:accepted_mineral_smelter_input'
'#forge:cobblestone'
'#minecraft:stone_crafting_materials'
'#minecraft:stone_tool_materials'
'#quark:stone_tool_materials'
'@minecraft'
'%building_blocks'

**Comment by MongoTheElder** [comment]
Looking at a number of other item types, the {Charged:0b} tag is present on all of them.
