### ISSUE TITLE
Crash when crafting framed drawers with some blocks

### ISSUE THREAD

**Issue by Sunekaer** [Buuz135/FunctionalStorage#113]
Describe the bug
    The game crashes when trying to craft Framed compacting drawer with Stripped dark oak and stripped spruce. Also crashes when using some chipped blocks.

Steps to reproduce
    Craft Framed compacting drawer
    Add stripped dark oak, stripped spruce and framed compacting drawer in crafting table.

https://pste.me/@/B_FwpBjjhUs

**Comment by akoimeexx** [comment]
Also occurs with blocks from CoFH Thermal series mods, such as Signalum, Lumium, and Enderium blocks. Oddly enough, does not crash with the Constantan blocks provided in the mod.

Discovered while playing StoneBlock 3 modpack:

AdoptOpenJDK jdk-11.0.6.10-hotspot
Minecraft 1.18.2
Forge 40.1.184
Functional Storage 1.18.2-1.0.7
Thermal Series 9.0.0.32

**Comment by Buuz135** [comment]
Fixed in https://github.com/Buuz135/FunctionalStorage/commit/aaf9b4f22d01fadc2ea893340eea30f49df83c4e
