### ISSUE TITLE
Puller Upgrade doesn't like compacting drawers

### ISSUE THREAD

**Issue by ShyNieke** [Buuz135/FunctionalStorage#115]
![image1](https://user-images.githubusercontent.com/7694658/200368938-5839a936-1dec-467a-ab8b-1fb716171cc5.png)
![image](https://user-images.githubusercontent.com/7694658/200368948-66ef4c3d-8fd4-4d34-82ec-07d0f3a6ee24.png)

The puller upgrade doesn't seem to like pulling if it is inside a compacting drawer, have tried a vanilla inventory on all sides of the drawer with an iron block, ingot and nugget in the drawer itself and in the inventories and neither block, ingot or nugget would get pulled out even if the drawer was set and locked

**Comment by hvdklauw** [comment]
I just noticed the same!

Also pushing into an unset compacting drawer doesn't work either, once it's set and locked pushing works.

**Comment by Belgabor** [comment]
Seems like it can only pull into the bottom right (smallest) slot. If that is unset or not the item you are pulling it won't work.
