### ISSUE TITLE
Compacting copper

### ISSUE THREAD

**Issue by Sunekaer** [Buuz135/FunctionalStorage#119]
Modpack: StoneBlock 3
Mod version: functionalstorage-1.18.2-1.0.7.jar

    Compacting drawer empty.
    Put in a copper ingot - nugget does not display, and you can't put nuggets in
    Take everything out of the drawer and put a nugget in first.
    Now is will display and further ingots or nugget can be put in.

**Comment by Buuz135** [comment]
Can't replicate with just create, might be a conflicting recipe issue. When using a copper ingot it adds the nugget just fine.
