### ISSUE TITLE
Void upgrades in compacting drawer prevent additional storage upgrades from being removed

### ISSUE THREAD

**Issue by Visate** [Buuz135/FunctionalStorage#125]
Expected behaviour happens with regular drawers. You can still remove storage upgrades when there is a void upgrade in the other slot beyond the first upgrade.

In a compacting drawer, if you have 1 void and 1 storage upgrade, you can still remove the storage upgrade as expected. But once you add a second storage upgrade, no storage upgrades can be removed until you've removed the void upgrade.

Mod version: 1.18.2-1.0.6
Modpack: ATM7

**Comment by Buuz135** [comment]
Storage upgrades can't be removed if the current item amount is bigger than the capacity of the drawer when the upgrade is removed.
