### ISSUE TITLE
[1.19.2] Drawer Visual Item Render Issue

### ISSUE THREAD

**Issue by Mitchell5200** [Buuz135/FunctionalStorage#130]
Modpack: atm8 v1.0.3
Functional storage 1.19.2-1.0.7

The items fail to fully render on forge 43.1.57, but do on forge 43.1.55, pictured below are framed compacting drawers but it affects all FS drawers, and yes, Rubudium is installed in the pack, i do not have any shaders running at this time however

Forge 43.1.57
![2022-11-24_13 02 12](https://user-images.githubusercontent.com/45913837/203911854-1e97c087-344a-41b8-8ed2-b54ef4c19d05.png)

Forge 43.1.55
![2022-11-25_13 44 15](https://user-images.githubusercontent.com/45913837/203911907-e8e96104-c9fc-4703-bbc4-ccf7d3836a84.png)

**Comment by Rithenar** [comment]
AS I am having the same issue, I downgraded Forge to 43.1.55 but I am still experiencing the rendering issue.

![Screenshot 2022-11-30 070129](https://user-images.githubusercontent.com/9939332/204803029-111be8e4-821f-44fb-9068-02d3d73e040a.png)

**Comment by trephas** [comment]
Issue happens on forge 43.1.58 with Functional storage 1.19.2-1.0.7 also

**Comment by koukimonster91** [comment]
i would like to add on to this that when you go into spectate and fly into the drawer the items are still there, they are just not far enough forward to clip through the face of the drawer

**Comment by Darkfiend009** [comment]
I am having the same issue with a custom pack that i created.

Forge 43.2.0

![image](https://user-images.githubusercontent.com/42146629/207383170-66f39282-63dc-4dce-9d7b-f84ac7825fb0.png)

**Comment by Buuz135** [comment]
Forge issue https://github.com/MinecraftForge/MinecraftForge/issues/9216

**Comment by SmugTomato** [comment]
While the forge regression is responsible for the items not drawing I also found an issue with create shafts and cogs not displaying properly (in Forge 43.1.55). They are 3D objects in the world and inventory but aren't block-shaped, so the positioning for blocks doesn't work on them properly.

![2022-12-14_19 15 33](https://user-images.githubusercontent.com/38669186/207679609-51af9e49-638f-4b6b-87a1-28fd4afb1206.jpg)
![2022-12-14_19 15 36](https://user-images.githubusercontent.com/38669186/207679619-86beea7a-5c43-48ac-b16e-153c65f8ddb3.jpg)

It might be a better idea to position 3D items/blocks and squish them flat-ish to the center of the drawer face instead of offsetting them in the way you're currently doing, it should look pretty much the same for regular blocks but would allow irregularly shaped 3D items/blocks to display properly as well. Code below might explain what I mean better.

```java
BakedModel model = Minecraft.getInstance().getItemRenderer().getModel(stack, Minecraft.getInstance().level, null, 0);
if (model.isGui3d()){
    matrixStack.translate(0,0, someTranslationToCenterThingToFaceOfDrawer);
    matrixStack.scale(0.75f, 0.75f, 0.1f); // changed z-scale to 0.1 to squish model
} else {
    matrixStack.scale(0.4f, 0.4f, 0.4f);
}
```

**Comment by JakeMoe** [comment]
Just FYI, I think I'm seeing the same issue in DireWolf20 1.19; I just started moving from chests to drawers, and only cubed blocks are showing on the face of my drawers, the rest just have the numbers without an image of the item.

**Comment by DizzyDJW** [comment]
So when is the update that fixes this issue?

**Comment by SmugTomato** [comment]
It's a forge bug, it will be fixed when forge fixes it

**Comment by Speedy7524** [comment]
When will Forge fix it?  Does Forge even know about it?

**Comment by Buuz135** [comment]
Fixed in forge 43.2.3

**Comment by osirisgothra** [comment]
I am not sure if older packs can upgrade forge to resolve this issue, for them I offer this semi-workaround, which might be obvious to some but not others.

To remedy this situation

![image](https://user-images.githubusercontent.com/4777106/224579334-92475861-f142-4a35-9b45-fa6011e9a6e7.png)

Use the drawers that allow textures to be applied and use a transparent block for the drawer slot, here's an example:

![image](https://user-images.githubusercontent.com/4777106/224579207-fd831203-bcc7-477a-92f6-73dc9af19940.png)
_(be sure not to use chipped or other invalid blocks like fences or walls if you are in a version where that issue still exists)_

And you should be able to see the objects again like shown here:

![image](https://user-images.githubusercontent.com/4777106/224579003-b06ad92a-1f25-4f23-9c2b-d0f2b2f8f688.png)

This example was done in the latest (as of 3-12-2023) version of Stoneblock 3.

**Comment by derekmurawsky** [comment]
I'm having this same issue with All The Mods 9-0.2.27, which is running with Forge 47.2.16. It happens after I pull an item out of the drawer. It seems to reset if I unlock and then relock the drawer.
