### ISSUE TITLE
[Crash] Not Idiot proofed enough

### ISSUE THREAD

**Issue by walksanatora** [Buuz135/FunctionalStorage#132]
if you have something like lets say a turtle from CC: Tweaked and try to texture a framed drawer with it it will crash because it cannot find the side
[crash-2022-11-26_07.48.08-client.txt](https://github.com/Buuz135/FunctionalStorage/files/10095867/crash-2022-11-26_07.48.08-client.txt)

**Comment by Buuz135** [comment]
Duplicate #123
