### ISSUE TITLE
Armory NBT data too large.

### ISSUE THREAD

**Issue by DreiPixel** [Buuz135/FunctionalStorage#133]
hey im hosting a Stoneblock 3 server and on of my players couldn't join anymore because 1 armory had to much NBT data in it.

he had a mobfarm running and ripped the enchantments from the equipment and stored the books from it in a armory and after a while he couldn't join anymore because there was too much NBT data. 10 bytes over the limit. had to do a small backup restore.

dunno if it possible to add a limit how much nbt data can get stored.

**Comment by pakruse** [comment]
Googling led me to this ticket after having the same issue (also on Stoneblock 3). The Armory Cabinet is causing a kick loop when it has too much NBT data. No comments on the ticket otherwise, though - is this something that can be fixed by configuring the ARMORY_CABINET_SIZE to a lower value?

**Comment by DreiPixel** [comment]
i havent tried tbh but yeah that should work.
