### ISSUE TITLE
[1.18.2] Minecraft crash when i place simple compacting drawer

### ISSUE THREAD

**Issue by SyafiqYunus** [Buuz135/FunctionalStorage#144]
This issue is related to #143. Even after updating Functional Storage to 1.1.1 the game still crash if i try to place the said simple compacting drawer 

**Functional Storage Version :** 1.1.1

**Titanium Version :** 3.5.8.0-40

**Crashlog :** https://gist.github.com/SyafiqYunus/0883bf29df6eb2187ed67cc29461c717#file-crash-report-2-L5245

**Comment by Buuz135** [comment]
That will still happen with drawers used in 1.1.0, new drawers won't have that issue
