### ISSUE TITLE
Issue starting up Minecraft instance with Functional storage.

### ISSUE THREAD

**Issue by PhantomCrestTV** [Buuz135/FunctionalStorage#146]
**Failed to create mod instance. ModID: functionalstorage, class com.buuz135.functionalstorage.FunctionalStorage**

Currently trying to build a 1.18.2 pack with functional storage in it and I keep getting this error. Hope somebody can help! 

[latest.log](https://github.com/Buuz135/FunctionalStorage/files/10365309/latest.log)

**Comment by Buuz135** [comment]
Try updating titanium
