### ISSUE TITLE
[FEATURE REQUEST] Feature Item Content Preview in Compacting Drawers

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#149]
**Description:**
Just how we can see what is inside normal drawers. Would be useful to see the content of compacting drawers while on our inventory
![image](https://user-images.githubusercontent.com/44974827/212241102-7a703134-7d72-4544-8445-c3f9205ba6e1.png)
![image](https://user-images.githubusercontent.com/44974827/212241109-016e7885-2bc6-4a4f-8959-0f84d0f8a2bd.png)

**Comment by Buuz135** [comment]
Duplicate #48
