### ISSUE TITLE
Framed Drawer crash issue [1.18.2

### ISSUE THREAD

**Issue by Keonmagic22** [Buuz135/FunctionalStorage#151]
All of my mods are up to the latest version. I keep getting a game crash when I use Chipped blocks mainly framed planks.

Taking a quick look at the crash log it is saying something about "failed to get texture".

**Comment by Buuz135** [comment]
What is "latest" version, as you decided to ignore the template.

**Comment by Keonmagic22** [comment]
I Apologise for ignoring the template.
The version number is 1.18.2-1.0.8

I can give more information once I get home later today

**Comment by Buuz135** [comment]
There are more versions after that one, that's not the latests.
