### ISSUE TITLE
[1.19.2] Drawer Visual Item Render Issue

### ISSUE THREAD

**Issue by daymondsama** [Buuz135/FunctionalStorage#154]
Modpack: atm8 v1.0.8
Forge: 43.2.3
Functional storage 1.19.2-1.0.8

The sprites of honeycombs aren't showing in front, but blocks works fine and some others too.
View of the drawer:
![image](https://user-images.githubusercontent.com/56473315/213902901-c954da45-595c-4a07-8951-55935778b69a.png)

View of the inside of the drawer: 
![image](https://user-images.githubusercontent.com/56473315/213902941-f12ae346-fd48-47e5-b076-1251b091a0e8.png)

**Comment by Buuz135** [comment]
I think this should be fixed already
