### ISSUE TITLE
[1.19.2] Missing Controller Extensions

### ISSUE THREAD

**Issue by AaronSpinner** [Buuz135/FunctionalStorage#160]
I am missing the Controller Extension, i can not find it in the .jar file as well, did it get removed? I can not find anny Information to it :3

**Functional Storage Version:** functionalstorage-1.19.2-1.0.8.jar

**Titanium Version:** titanium-1.19.2-3.7.0-23.jar

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by DreaminBoi** [comment]
Heya!, it seems your FS is a bit outdated,could you update it to the new version?, iirc buuz added the extension in the newer version and also don't forget to update the titanium too to prevent any mishap

**Comment by AaronSpinner** [comment]
thx for your fast answer

Sadly i can not upgrade since the mod requieres a newer forge version then and i can not upgrade the forge version since i need this specific one for a couple of other mods wich do not support newer versions. Anny plans to add the extension to the older versions as well, otherwise i have to live with it, or switch back to storage drawers :)

greetings Aaron

**Comment by Buuz135** [comment]
The required forge version fixes all the item rendering that forge broke on the release build, but sure let me go and backport everything to another forge version because I'm soooooo scaaaaareeeed of one less user if you switched to Storage Drawers

**Comment by AaronSpinner** [comment]
I simply asked if there are plans to backport this, not if you would do it just for me... a simple "no there are no plans" would have been enough.
