### ISSUE TITLE
[1.19.2] Adding fluid with bucket does not consume bucket of fluid, cannot remove fluid unless bucket is in offhand.

### ISSUE THREAD

**Issue by kalutro** [Buuz135/FunctionalStorage#165]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.1.3

**Titanium Version:** 3.7.2-26

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

This issue occurs in the Cryptopolis modpack. I have raised the issue on their discord and was told to report it here.

"For reasons unknown, I am able to put fluid from a bucket into a Fluid Drawer without it consuming the bucket. In fact, if my offhand is empty, it will put the empty bucket there. There also seems to be an issue where I cannot remove fluid from a Fluid Drawer with a bucket. I will need an empty bucket in my offhand and an empty main hand to remove fluid."

![ezgif-5-027b4cd758](https://user-images.githubusercontent.com/69569507/221686849-47889b85-918c-4cdc-b62d-521864706dea.gif)

![javaw_RpjslXPXww](https://user-images.githubusercontent.com/69569507/221685077-114abc7c-6ed8-43ac-a425-d088c03add95.gif)

**Comment by MuteTiefling** [comment]
I'm able to reproduce this as well. 

https://streamable.com/b9glnn

**Comment by Jonius7** [comment]
Same issue happening in 1.18.2. 
Also the bug will **overwrite** whatever is in your offhand with an empty bucket, i.e. you lose the item in your offhand.

**Comment by Buuz135** [comment]
This doesn't happen with just the mod, something else is changing the beheviour.

**Comment by Saereth** [comment]
This is also happening in ftb skies 1.19.2 so I'll try to start looking for mod similarities between the packs to see if we can narrow it a bit.

**Comment by MuteTiefling** [comment]
With the added information in https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3057 I'm able to reproduce this with only Functional Storage and JEI.

The key is the shield.

https://streamable.com/iq73dd
