### ISSUE TITLE
[1.18.2] Stoneblock 3 - Copressing Cobble [Cyclic]

### ISSUE THREAD

**Issue by spooky-ddos** [Buuz135/FunctionalStorage#166]
I have installed the Cyclic mod to the Stoneblock 3 modpack, but there is an issue with the compression of cobble in the Compacting drawer. Normally, I can create compressed cobble from the Ftbstoneblock mod through normal crafting, but when I put cobble into the drawer, it compresses it to cyclic compressed cobble instead. I have tried putting compressed cobble from the Ftbstoneblock mod into the drawer, but it sets it to the lowest level and compacts it into 2x and 3x cobble. I have tried to search for information about compacting rules, but I do not understand how to use them. Is there any way to fix this issue?

**Comment by Buuz135** [comment]
Use the other mod cobblestone first to configure the drawer
