### ISSUE TITLE
[1.18.2] Redstone upgrade outputting 0-197 redstone power instead of 0-15

### ISSUE THREAD

**Issue by adam-drake1** [Buuz135/FunctionalStorage#171]
This is visible when connecting a comparator to the drawer. Looking at DrawerBlock.java it appears you're multiplying the amount by 14 twice.

**Functional Storage Version:**
1.18.2-1.1.3

**Titanium Version:**
3.5.8

**Comment by Zonk1987** [comment]
![2023_05_11_04_02_30_Direwolf20_1 19](https://github.com/Buuz135/FunctionalStorage/assets/25836879/68f31660-9cd7-47d6-a719-3ade64c72c6a)

Same problem in 1.19.2 and when a External Storage from Refined Storage is attached to the Draw i can't get any items in or out and the the Items don't stack anymore.

Functional Storage Version:
functionalstorage-1.19.2-1.1.3

Titanium Version:
titanium-1.19.2-3.7.3-27

Modpack Version:
Direwold20 1.19 - 1,9,0
