### ISSUE TITLE
[1.19.2] Cannot store Pumpkin Pie in a drawer

### ISSUE THREAD

**Issue by RadicalGDPRist** [Buuz135/FunctionalStorage#172]
**Functional Storage Version:** 1.19.2-1.1.3

**Titanium Version:** 3.7.2

Modpack: All The Things 8 1.0.15

I cannot store Minecraft's Pumpkin Pie in a drawer (minecraft:pumpkin_pie). I tried:

- single and 2x2 drawers
- right-clicking the drawer (places pumpkin on the ground or nothing happens if in air) and opening the drawer UI (cannot be clicked inside the slot in any way)

**Comment by Glittersword** [comment]
Had a similar issue on items that activate on Right click.  I had the drawers set up as extra storage for Refined Storage system and piped the item into the drawer for the first item then locked the drawer and used Refined Storage to put the items in.  It is a workaround I know and it requires compatibility with another mod but it works.  Hope this helps.

**Comment by Buuz135** [comment]
It's an issue with a mod that makes them be able to be placed, without any other mods it works fine
