### ISSUE TITLE
[1.19.2] Issue Framed draw with birch logs crash when mined

### ISSUE THREAD

**Issue by Deathcoat101** [Buuz135/FunctionalStorage#173]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**
[crash-2023-04-13_16.03.19-client.txt](https://github.com/Buuz135/FunctionalStorage/files/11218984/crash-2023-04-13_16.03.19-client.txt)

I tried making Framed drawers with Birch logs and birch planks. The first 20 I shift clicked to inventory disappeared. I shift clicked and made another 22 but the birch plank interior texture didn't load when I placed them. When I tried to left click the broken textured framed drawers it crashes the game, and loads the fore mentioned crash report. I was able to right click over the draw, so I cardboard boxed it and placed in a chest.

**Comment by thepriz** [comment]
Functional Storage Version: 1.19.2-1.1.4

Titanium Version: 1.19.2-3.7.3-27

Crashlog If Applicable (Upload to pastebin/gist)
[Minecraft 1.19.2 Functional Storage Crash Part 1](https://pastebin.com/A4WEs0tY)
[Minecraft 1.19.2 Functional Storage Crash Part 2](https://pastebin.com/A6ymaRft)

I also experienced this bug. I had placed 256 drawers all made out of Framed Drawer (1x1) and oak planks. I placed the next one and it placed but the front of the drawer just showed a wire mesh but the sides all had the oak planks texture. I tried to remove the drawer with an axe and the game crashed with the same crash as above.
