### ISSUE TITLE
[1.19.2] Locking a drawer caused it to face West

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#174]
DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
-**Functional Storage Version:** 1.19.2-1.1.3
**Titanium Version:** 3.7.3
Carry On: 2.0.5.10
Forge: 43.2.8

When I lock a drawer, it causes the face of the drawer to face West.
And when I break it, or use the Carry function from Carry on, to replace it in the correct orientation, it becomes unlocked. 
![image](https://user-images.githubusercontent.com/44974827/232184012-b36a87dd-7955-4aef-a627-4f8bd161e233.png)
![image](https://user-images.githubusercontent.com/44974827/232184062-006b3ff3-9507-434b-84a4-a9446ef90160.png)

**Comment by Buuz135** [comment]
Please don't use carry on to move them just break them as they wont loose their items. Did you move it before doing that?
