### ISSUE TITLE
[1.19.2] Issues depositing items into drawers

### ISSUE THREAD

**Issue by bbf** [Buuz135/FunctionalStorage#175]
**Functional Storage Version:** functionalstorage-1.19.2-1.1.3.jar

**Titanium Version:** titanium-1.19.2-3.7.2-26

**Crashlog If Applicable (Upload to pastebin/gist):** none

Hello,

I'm running ATM-8 (latest 1.0.15) and I have the following issue on my server: drawers refuse to accept more items.

I have several drawers that are connected to a controller, with extensions, and even a Refined Storage external bus connected to an extension. Among my drawers I have some with no upgrade, some with void upgrades, some with storage upgrades and some with both types of upgrades. The issue happens with all the drawer no matter which upgrade types.

I tried to isolate to find any common pattern. After the drawer is bugged, even if I take down (break) the controller, the drawer still refuses to accept more items.

![image](https://user-images.githubusercontent.com/158033/232652649-dce885ec-e172-4b45-b116-00abf76d0c76.png)

If I try to instead of depositing, to withdraw first something, and then deposit, it sometimes works. There's some temporal connection here as well, because after some arbitrary time, the drawer will stop working again. I'm currently leaving the controller down to see if without it I can cause the same issue. If not, I imagine it could be something interacting with the controller.

How can I help you further isolate the problem? Would a save share help? I can even dump the NBT from a drawer in a world save if you want, just let me know what I should be looking for.

I have reported the bug also on ATM-8: https://github.com/AllTheMods/ATM-8/issues/1248
... even accidentally confused sophisticatedstorage with functionastorage /facepalm :)

**Comment by Buuz135** [comment]
Sorry for the late response, I would need logs and I dont think you will have them months later

**Comment by bbf** [comment]
I recently started a new season of ATM8. I've been avoiding using drawers for storage because of this, but I can try again and report if the bug is still present. If it happens, do you think this time you'll have time to look into it?
