### ISSUE TITLE
[1.19.2] Incorrect counts reported when using Jade

### ISSUE THREAD

**Issue by Epic428** [Buuz135/FunctionalStorage#176]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.1.3

**Titanium Version:** 3.7.3-27

**Crashlog If Applicable (Upload to pastebin/gist):**
I noticed this while playing on FTB Skies latest version. The amounts listed in Jade are off from the amounts listed in the drawer.

![image](https://user-images.githubusercontent.com/291578/232976832-30b8841f-6baf-46a4-9c58-a37616e947c0.png)

**Comment by Satherov** [comment]
I think this is just because it only shows one decimal place on the drawer on just rounds up or down. I personally wouldn't call it a bug, just a minor visual discrepancy

**Comment by Buuz135** [comment]
Yeah, just different ways of rounding
