### ISSUE TITLE
[FEATURE REQUEST] A way to move drawers with stuff in them already (ATM7 - 1.18.2) 

### ISSUE THREAD

**Issue by llloyd4** [Buuz135/FunctionalStorage#185]
**Description:**
Hi! Think you could add packing tape or a dolly so we can move our drawers ? Would make remodeling easier. >.<

**Comment by Satherov** [comment]
Idk what's different from you but I'm currently playing ATM7 to the sky and when I brake a drawer it keeps the items inside

**Comment by Buuz135** [comment]
That is troo
