### ISSUE TITLE
[1.19.2] Redstone Upgrade

### ISSUE THREAD

**Issue by mandrake-gull** [Buuz135/FunctionalStorage#190]
**Functional Storage Version: 1.1.3**

**Titanium Version: 3.7.3-27**

The redstone upgrade (which is a great feature) emits a level up to 200, normal redstone is built to handle a level up to 15. So when using this for automation you get a small fraction of drawer filled instead of the full thing.

Thank you for your great work on the mod.

**Comment by JDLanyon** [comment]
I also have this issue in 1.18.2.
