### ISSUE TITLE
[1.19.2] Drawers render differently depending on facing location

### ISSUE THREAD

**Issue by BrewingCoder** [Buuz135/FunctionalStorage#192]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**
1.19.2-1.1.4

Drawers facing East/West render darker than drawers facing North/South.

Attached is a screen shot from FTB Skies.  Shaders are turned off and there are no resource/texture packs. 

The drawers are so dark they look like a different block.  

EDIT: I've added light source blocks directly above/below and onto the West facing to show that it's not shadow/lack of light causing the issue.

![functional_Storage_example](https://github.com/Buuz135/FunctionalStorage/assets/6723474/a9972fa4-f346-46cd-81e5-f7d2e0ca8cfc)

**Comment by Buuz135** [comment]
#33
