### ISSUE TITLE
[1.18.2] Shift-Right-Click Front Progresses Drawer Break

### ISSUE THREAD

**Issue by AefRal** [Buuz135/FunctionalStorage#193]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
-Is up to date.

**Functional Storage Version:**
-functionalstorage-1.18.2-1.1.3.jar

**Titanium Version:**
-titanium-1.18.2-3.5.8-40

**Crashlog If Applicable (Upload to pastebin/gist):**
-Not a crash.

-Whenever I Shift-Right-Click to get a full stack from a drawer, 
I get one stack then the next hit causes damage(break % goes up.).
I would need to click off of the drawer to reset the % before getting 
another stack.
![2023-07-03_03 55 23](https://github.com/Buuz135/FunctionalStorage/assets/68062495/5213f80f-7d31-45e1-836f-6e7338ccfd70)
Modpack: All the Mods 7 - To the Sky - atm7sky

**Comment by Buuz135** [comment]
Remove the squirt gun mod left click keybind

**Comment by AefRal** [comment]
Such an easy fix. Thank you!
