### ISSUE TITLE
Functional Storage - 1.20.1-1.2.0 don't load correctly

### ISSUE THREAD

**Issue by Danmarcos99** [Buuz135/FunctionalStorage#195]
I have an issue to load the mod in Forge 1.20.1-47.1.0. When I try to load the game I recive this message
![image](https://github.com/Buuz135/FunctionalStorage/assets/139653367/14dc7965-7e5c-474c-b5a9-20a4427f519c)
I don't know why the mod isn't loading correctly, here I leave the list of the other mods if this is a incompatibility between 2 mods
![image](https://github.com/Buuz135/FunctionalStorage/assets/139653367/d0782946-7ec8-4668-a34b-0a65126069f6)

I hope someone know what is failing and can help me to load correctly the mod.

**Comment by Buuz135** [comment]
Im would need the log to know what its happening

**Comment by Mjolinir** [comment]
[crash-2023-07-15_17.47.02-fml.txt](https://github.com/Buuz135/FunctionalStorage/files/12062876/crash-2023-07-15_17.47.02-fml.txt)

**Comment by Buuz135** [comment]
Downgrade titanium a version

**Comment by Mjolinir** [comment]
This did resolve the issue for me. Thank you! Should a bug report be done for Titanium, or ?

**Comment by Danmarcos99** [comment]
> Downgrade titanium a version

Yeah, it worked. Thanks :)

**Comment by Buuz135** [comment]
I will leave the issue open here
