### ISSUE TITLE
[1.18.2] Items taken from simple compacting drawers are different from non-compacting drawer Items

### ISSUE THREAD

**Issue by ScidaJ** [Buuz135/FunctionalStorage#199]
**Functional Storage Version: 1.18.2-1.1.3**

**Titanium Version: 3.5.8**

The title is self-explanatory, but I also recorded me testing it. https://youtu.be/81WNJhszpzk

**Comment by Buuz135** [comment]
Another mod is messing with the empty ItemStack and adding nbt to it, causing the drawers to get strange nbt values when moved.
