### ISSUE TITLE
[FEATURE REQUEST] Feature make already filled drawers priority when piping into drawer controller

### ISSUE THREAD

**Issue by Dustybonss** [Buuz135/FunctionalStorage#200]
I noticed that a thread was opened over a year ago about drawers that already have items in them not being the priority, i have a mob farm in FTB Skies, when i used StorageDrawers in the past i would leave one Unlocked drawer as an overflow into a chest or larger storage block to help sort, but that seems impossible as normal items that are already in the drawers are being thrown in the unlocked drawer aswell.

Main suggestion as this seems to be gone unoticed is to make drawers with items already in them be priority with the drawer controller/Extenstion, Then fill unlocked drawers after if no locked drawer can accept the item, if the drawer has a void upgrade it would void the exess of that specific item as you wouldnt want that to be in the overflow.

**Comment by Buuz135** [comment]
Duplicate #103
