### ISSUE TITLE
Crashing when vewing compacting drawers' contents in inventory

### ISSUE THREAD

**Issue by penturt** [Buuz135/FunctionalStorage#210]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**
functionalstorage-1.19.2-1.1.7
forge-1.19.2 - 43.2.23

**Titanium Version:**
titanium-1.19.2-3.7.3-27

Not sure if i directly has to do with Function Storage, but its the only common mod that seems to cause the crash, server does not crash just the client.

in short, so far its only happened with regular compacting drawers and simple compacting drawers, but whenever i have compacting drawers with a very large amount of items (such as lapis, redstone, diamonds, etc... ) in my inventory and i mouse over them to see the contents the client freezes and crashes.

I'm able to break the compacting drawer, pick it up, and if lands into my hotbar i able to place it back down. But, if i break it down, pick it up and it goes into my inventory (or even hotbar) and then i go to my inventory, and i want to view the contents of it before placing, or simple pass the pointer over the compacting drawer(s) by mistake the client freezes and crashes. I'm playing on a forge server i host, nothing happens to the server it just seems to be client side. I attached the latest crash report, hoping it tells you something.

[crash-2023-09-16_01.16.25-client.txt](https://github.com/Buuz135/FunctionalStorage/files/12643265/crash-2023-09-16_01.16.25-client.txt)

**Comment by phit** [comment]
same issue on functionalstorage-1.20.1-1.2.3, titanium-1.20.1-3.8.21

https://gist.github.com/phit/388bc75a010fc759a71f2154b63d79c0

**Comment by gcosta0410** [comment]
Same here. I've run some tests: If I mine a drawer with items but no upgrades and then hover over it while on my inventory, everything is fine, but as soon as I add a void upgrade, I can no longer hover over it without crashing.
[crash-2023-10-14_01.17.45-client.txt](https://github.com/Buuz135/FunctionalStorage/files/12900653/crash-2023-10-14_01.17.45-client.txt)

**Comment by Buuz135** [comment]
If you are running the 1.19.2 version you should update the mod. you say you are using 1.1.7 but the crash has 1.1.6 @penturt
