### ISSUE TITLE
[1.20.1] Storage Drawers not holding (some) Mob-drops to capacity with upgrades

### ISSUE THREAD

**Issue by Nick-77ab2** [Buuz135/FunctionalStorage#221]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.2.3 (Issue not in the 1.2.4 changelog) also 1.2.4 (checked in solo world)

**Titanium Version:** 3.8.22

**Crashlog If Applicable (Upload to pastebin/gist):**

Cannot place any more slimeballs in any 1x1 or 2x2 drawer past numbers around this amount (some 2x2's stop around 700, some around 900). Not sure what's going on but I'm pretty sure this isn't intended.

I checked with cobblestone and it seems fine, just weirdly slimeballs. Same occurs with spidereyes after checking. The issue might be mob-drop related.

Edit: Rotten flesh is fine, so are eggs. After waiting a bit I got one of the drawers to accept more slimeballs, and then it went back to the state of not accepting any more. This seems to actually be on some sort of cycle. I've even got one stuck at 64 slimeballs and i cannot place more in until the "cycle" goes back to allowing me to place them there.

![Screenshot_1567](https://github.com/Buuz135/FunctionalStorage/assets/8357073/5938b20a-0cd0-459f-b7f8-b36772412bec)
![Screenshot_1568](https://github.com/Buuz135/FunctionalStorage/assets/8357073/bba89d90-0cf4-4014-9362-b23c44eee6db)
![Screenshot_1569](https://github.com/Buuz135/FunctionalStorage/assets/8357073/e50fdbf0-d318-492a-b5c1-1a843348542d)

**Comment by Nick-77ab2** [comment]
This is in the direwolf20 pack so I decided to post this before deciding to completely update the pack and server i host myslef.

**Comment by Buuz135** [comment]
Are the items in the drawers or the ones you trying to insert have random nbt?

**Comment by Nick-77ab2** [comment]
> Are the items in the drawers or the ones you trying to insert have random nbt?

I don't believe they do, I haven't messed with the slimeballs. The same slimeballs that couldn't be placed into a drawer at one point could be at a later point, again only up to a certain value before it stopped allowing more to be placed in.

**Comment by Nick-77ab2** [comment]
@

> Are the items in the drawers or the ones you trying to insert have random nbt?

Checking more into this, yes something is adding an nbt tag to these items. They 
![!1](https://github.com/Buuz135/FunctionalStorage/assets/8357073/d612dff6-3836-4c14-8804-d60396b61dcd)
stacked in the AE storage system i had setup and apparently pulled out first. After looking through the tags both in my server and on a test world (forgot about f3+h) and checking the data I resulted in this: 
Server, slimeballs with issues:
![!1](https://github.com/Buuz135/FunctionalStorage/assets/8357073/5bbe2035-2ce1-403f-9468-402068b914b5)

local test slimeballs no issues:
![!2](https://github.com/Buuz135/FunctionalStorage/assets/8357073/7b630fd3-3c6e-411a-a027-8c271cb252ca)

Problematic nbt tag:
![Screenshot_1578](https://github.com/Buuz135/FunctionalStorage/assets/8357073/e82361a4-dd49-490b-994b-8108aa485d3d)

So yes you were right.
