### ISSUE TITLE
[1.20.1] Create mod Threshold Switch

### ISSUE THREAD

**Issue by TeoH1gh** [Buuz135/FunctionalStorage#229]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.2.5

**Titanium Version:** 3.8.23

**Crashlog If Applicable (Upload to pastebin/gist):**

When using the threshold switch from the Create mod it reads the drawers as full as soon as you input a stack of items. With the storage drawers mod it can correctly read the fill percentage of a drawer.

**Comment by Matyrobbrt** [comment]
Duplicate of #217.

**Comment by bloodscon** [comment]
the create threshold switch does not like the Void upgrade if you have no void upgrade in the drawer I have noticed the switch works fine
