### ISSUE TITLE
[1.20.1] Missing Top Texture with Tooltip

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Buuz135/FunctionalStorage#236]
**Functional Storage Version: 1.2.6**

**Titanium Version: 3.8.23**

When hovering over a drawer, the tooltip will not display the top texture of blocks. The screenshot only shows this happening with logs, but I see the same issue with planks and slabs.

<img width="1415" alt="Screenshot of issue" src="https://github.com/Buuz135/FunctionalStorage/assets/64599476/fdf68d61-a547-4507-bc64-f75f48a9f126"/>

**Comment by Buuz135** [comment]
The texture is there, its just too dark
