### ISSUE TITLE
[FEATURE REQUEST] Right-click (not left) to fill a bucket from a Fluid Drawer

### ISSUE THREAD

**Issue by trevorjd** [Buuz135/FunctionalStorage#237]
**Description:**

Hi Buuz,

Request:  Use right-click to fill a bucket from Fluid Drawer

Justification:  MC players have been trained to right click to interact with things.  e,g, filling and emptying a bucket with water or lava uses right-click not left click.  Vanilla does it.  All the modded tanks I know of do it.  Indeed you put fluid INTO a Fluid Drawer with a right-click. 

By not following this well-established tradition, frustration is created.  I just spent the best part of an hour troubleshooting with AllTheMods9, trying to determine whether there was a bug to report.  The same question being asked many tines.  I finally found a chance mention in your discord that I have to hold the bucket and PUNCH with it!

**Comment by Buuz135** [comment]
That would only work with buckets, but with tanks like the Mekanism tank you wouldnt be able to fill the tank as they have a fill limit.
