### ISSUE TITLE
[BUG] Items aren't inserted if their slot reads 0

### ISSUE THREAD

**Issue by jarquafelmu** [Buuz135/FunctionalStorage#24]
Minecraft: v1.18.1
Forge: v39.1.2
Functional Storage: v0.0.10

I am having a problem where I double right-click on the storage controller with an empty hand to store all of my items, even if an item is assigned a slot, if that slot reads 0 it counts as not being there. 

If I right-click that same item onto the controller, then it will find a new spot for the item instead of the placing it in the existing spot.

**Comment by Buuz135** [comment]
Can't replicate in v0.0.11
