### ISSUE TITLE
[1.20.1] Puller Upgrade not working on Fluid Drawer and Caldrons

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#244]
**Functional Storage Version:** 1.20.1-1.2.6
**Titanium Version:** 3.8.25

From my understanding, it should be able to pull fluids using the upgrade and have a tank next to the drawer. 
I even installed [Capable Cauldrons](https://www.curseforge.com/projects/826695) by King Lemming which improves the fluid interaction on caldrons.
![image](https://github.com/Buuz135/FunctionalStorage/assets/44974827/34f0c14c-21b0-4a1f-88a7-4418b5f7db49)
![image](https://github.com/Buuz135/FunctionalStorage/assets/44974827/1786603d-ac93-424b-bd9e-5d7c4a633411)

**Comment by Matyrobbrt** [comment]
The puller upgrade only attempts to pull 500mb at a time, while the cauldrons in capable cauldrons (and NeoForge in 1.21) only allow extractions in full buckets (1000mb) at a time. The fix is to change the configuration of the Functional Storage and update the `UPGRADE_PULL_FLUID` value to `1000`.
