### ISSUE TITLE
[1.18.2] Can't add recipe for chests from Sophisticated Storage

### ISSUE THREAD

**Issue by altano** [Buuz135/FunctionalStorage#246]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** version 1.1.3 (I'm running the latest version of "All The Mods 7: To The Sky" as of today, but I don't know if it's the most recent version of this mod)

**Titanium Version:** Sorry I have no idea what Titanium is.

**Crashlog If Applicable (Upload to pastebin/gist):** n/a

The basic issue is that you can't add recipes for Sophisticated Storage chests to the crafting interfaces. The most base level chest works but nothing else. For example, this simple recipe for the "Oak Iron Chest" from Sophisticated Storage:

<img width="545" alt="image" src="https://github.com/Buuz135/FunctionalStorage/assets/1009/1b0896a8-ed87-4d38-b321-4f637739ee41">

Results in this error when placed in a vanilla minecraft crafting table:

<img width="725" alt="image" src="https://github.com/Buuz135/FunctionalStorage/assets/1009/4f9dc2e6-3d36-477a-895e-69fad533d621">

The recipe for the "Oak Chest" from the same mod works fine (1 regular chest and 1 redstone torch) but I can't get any of the others to work.

**Comment by Buuz135** [comment]
Wrong mod

**Comment by altano** [comment]
Wow my brain isn't working right now, sorry. I have no idea why I posted this here. Sorry for the noise.
