### ISSUE TITLE
[Bug] Item duplication if installed alongside mod that adds additional compaction levels

### ISSUE THREAD

**Issue by MattDahEpic** [Buuz135/FunctionalStorage#25]
When installed alongside a mod that adds compression levels greater than vanilla, breaking and re-placing a compacting drawer causes the item in the top of the drawer to end up on the bottom right with the count of the item originally on the bottom right.

## Expected behaviour
Breaking and re-placing the compacting drawer retains the contents as it was placed before.

## Actual behaviour
Breaking and replacing the compacting drawer returns a different type of item in each slot but with the same counts as previously.

## Reproduction steps
1. Place a compacting drawer and fill it with 81 iron nuggets (aka 9 ingots or 1 block).
2. Break the compacting drawer with a pickaxe so it drops as an item containing its contents.
3. Re-place compacting drawer
4. Note that the compacting drawer now contains 81 iron blocks, 9 compressed iron blocks, and 1 double compressed iron block. The item in the top, most compressed, slot has shifted to the bottom right, least compressed, slot while maintaining the count of the item originall there (the iron nuggets).
5. Break the compacting drawer with a pickaxe again.
6. Place it again
7. Note that the drawer now contains 81 double compressed iron blocks, 9 triple compressed iron blocks, and 1 quintuple compressed iron block. This process will continue until the item in the top slot no longer has a 3x3 compression recipe. The issue does not occur if the item does not compress further than 3 levels (nugget, ingot, block).

## Additional info
Issue was discovered while playing All The Mods 7 version 0.3.1.

Minimal reproduction setup:
Minecraft 1.18.2
Forge 40.0.36
Functional Storage 0.11
[AllTheCompressed](https://www.curseforge.com/minecraft/mc-mods/allthecompressed) 1.0.6-1.18.2-40.0.31

**Comment by LunarLust** [comment]
Adding on that I've also experienced this even when inserting less than a block's worth of an item. A single nugget will become a full block and so on with these steps.
