### ISSUE TITLE
[1.20.1] Item's won't go into drawer?

### ISSUE THREAD

**Issue by ClickErrorxD** [Buuz135/FunctionalStorage#251]
**Functional Storage Version:** functionalstorage-1.20.1-1.2.8

**Titanium Version:** titanium-1.20.1-3.8.25

**Crashlog If Applicable (Upload to pastebin/gist):** N/A - not causing a crash

My items aren't going into drawers (via pipes or manually do it). Even if I manually do it, I need to take the item out first before right-click deposits what was already in my inventory. https://imgur.com/a/VdkncN7

I am getting mixed results, i am playing atm9, and made a post on their github too, here's the information there:

Issue: The issue is that something is adding the NBT Tag "{Picked:1b}" to a lot of items, making them not stack with the vanilla unmodified item. For example, if I have ender pearls, from the base game, and put them into the storage, and then something in the pack applies the data to the enderpearl, it will not stack with the vanilla ones in my drawer. I am using Spawners and Cursed Earth dirt to spawn mobs in.

It's not just Ender Pearls, it's a variety of items. I have items coming in from a fortune clearing quarry, and the mob farm mentioned above.

Pack Version: 0.2.40

Media:
The NBT Data on the Enderpearl is shown with the clip.
https://imgur.com/a/JX52bAh
https://imgur.com/a/Wglu3Wk

I just don't understand... I just had two different slime pearl items, same lore, same name, no nbt data, but they refused to stack, and then when I manually took the item out of the drawer, and put them back in, they stacked. However, my slime balls, same deal, no nbt data, but refused to go into my drawer of slime balls (with a available space).

I made this post with this exact issue in discord:
`Has anyone ever had issues with function storage? My items are not going into my drawers while im piping them into the controller, or when I right-click it to manually store it, it wont go in until I take the item out to add it to the stack in my inventory and then I can right-click again for it to deposit?

https://imgur.com/a/d0p1YVR

Here's the clip --- and I just realized, i think its the same issue i posted about before... items are getting a weird nbt data which makes them not stack, despite being the exact same item. If I put two of the same items (that don't stack) inside a pipz filter, one of them has no data, one has the data "{Picked:1b}". https://imgur.com/a/JX52bAh the clip of linked drawers and the nbt data picture`

**Comment by Buuz135** [comment]
Some mod is adding NBT to the empty stack, nothing I can do about it
