### ISSUE TITLE
[1.20.1] Compacting Drawers seems locked always

### ISSUE THREAD

**Issue by loulou1310** [Buuz135/FunctionalStorage#252]
Functional Storage Version:1.20.1-1.2.8

Titanium Version:3.8.25

ModPack:ATM9 9-0.2.39

Crashlog If Applicable : No crash

Issue : Item don't go inside any compacting drawer unless items are already present in compacting drawer.

To reproduce : Place unlocked compacting drawer in world, place hopper into it, place any item in hopper. Item stay in hopper.

Tested with : Compacting Drawer, Simple Compacting Drawer / Hopper, Integrated Dyn exporter, Modular Router

I found out about this trying to compress all combs into combs blocks with only one drawer. With non compacting drawers, the issue is not present.

**Comment by Buuz135** [comment]
This is how they work, they need to be configured first
