### ISSUE TITLE
GUI texture files unfindable? 

### ISSUE THREAD

**Issue by ThePhoenixIO** [Buuz135/FunctionalStorage#253]
I'm making a texture pack and was wanting to adjust the GUI textures for the drawers but can't find the GUI textures in any of the files. Are they procedurally generated via the code or where are the files located?

**Comment by Buuz135** [comment]
All the textures are located in the library Titanium, if you change the assets there it will be changed in all of the mods that uses it (Industrial Foregoing, Functional Storage, Sushi Go Crafting, ...) as they are generated in runtime with the assets there.
