### ISSUE TITLE
[FEATURE REQUEST] Linking Range expansion with Access Point

### ISSUE THREAD

**Issue by akama-aka** [Buuz135/FunctionalStorage#257]
**Description:**

Hello, I'm pretty new to this mod and I noticed that there is no real method to cover longer ranges. At first I thought that you could increase the linking range with the controller access point, which also makes more sense. However, I found out that it is for something else. I would like to see a block or upgrade like this where you can increase the range because on fairly large farms that can save a lot of work, space and more.

**Comment by Buuz135** [comment]
The controller range can be extended with upgrades. Thats not the point of access points.

**Comment by akama-aka** [comment]
> The controller range can be extended with upgrades. Thats not the point of access points.

How is that possible or is there any documentation for it? Because I couldn't find any Upgrades for this mod.
