### ISSUE TITLE
[FEATURE REQUEST] Rename Drawer Extension

### ISSUE THREAD

**Issue by krisavi** [Buuz135/FunctionalStorage#259]
**Description:**
Drawer extension should be renamed as it actually doesn't extend anything. More accurate could be proxy or access point. Currently there are quite many people asking how to link drawers to extension or how to extend range to higher than 12 blocks, etc. Renaming it to something more sensible could reduce the confusion about it's usage.

**Comment by DreaminBoi** [comment]
It's already renamed to drawer access point in https://github.com/Buuz135/FunctionalStorage/blob/main/CHANGELOG.md#version-126
