### ISSUE TITLE
[1.20.1] East/West facing drawers do not calculate lighting correctly

### ISSUE THREAD

**Issue by Chezzik** [Buuz135/FunctionalStorage#260]
**Functional Storage Version:**
functionalstorage-1.20.1-1.2.8

**Titanium Version:**
titanium-1.20.1-3.8.25

[Demonstration image](https://i.imgur.com/grUhGYO.png)

The drawer on the left side calculates light correctly (it matches the stone around it).  The drawer on the right does not.

I found this while playing Stoneopolis (version B2.0).  I'm using drawers with 'minecraft:stone' as the front face.  When I place them in North-facing or South-facing walls, they look great, but in East/West walls, they frequently are very dark, and in some cases nearly completely black.

If I place an East-facing drawer in the air, it is fine.  It is only when solid blocks are placed above, below, to the left, to the right, or any of the 4 diagonal positions (eg. up-right) that the light calculation is incorrect.  The more blocks placed in these 8 positions, the darker the drawer face becomes.  

Dynamic Lights (mod) is included in this pack (allows torches in hands to light the world), but I don't think it is to blame.

**Comment by Buuz135** [comment]
https://github.com/Buuz135/FunctionalStorage/issues/33

**Comment by Chezzik** [comment]
This needs to be reopened.

The other bug was closed without a fix.  A workaround was given, but the workaround:

1. Requires turning on a different lighting engine, which will likely cause issues with other mods.
2. Requires changing a config file that gets rewritten when Forge starts up, so it's not a workable solution for those of us who don't want to recompile forge.

At the very least, I would like to see an explanation for why no other mod needs this experimental option turned on, yet FS does.
