### ISSUE TITLE
[1.20.1] Mod Interaction - Added NBT to stored items when moved with Packing Tape

### ISSUE THREAD

**Issue by loving2** [Buuz135/FunctionalStorage#263]
**Functional Storage Version:** 1.20.1-1.2.10

**Titanium Version:** 1.20.1-3.8.27

Applying packing tape (from the Packing Tape mod) to a Functional Storage drawer with items in it and then removing the packing tape results in the items having an additional NBT tag. 

Running `/data get entity @s SelectedItem` shows that the NBT tag is `tag: {data_model: {}}`

I have no idea where this tag comes from, but it seems to be a mod interaction. I'm playing on ATM9 v0.2.54

I also made an issue on the Packing Tape github, since I'm not sure who would be able to help with this.

**Comment by Buuz135** [comment]
Another mod is addding NBT to the empty tag, its very hard to track who but not a mod issue. You dont need to use tape to move the drawers, you can just break them and that wont happen.

**Comment by loving2** [comment]
I can do the same procedure with a Limited Barrel from Sophisticated Storage and the stored items don't get that empty tag. Someone mentioned it happening to them, and I could easily recreate it. I wanted to at least make you aware that there seems to be an interaction out there with Functional Storage and something else that adds empty tags to items.
