### ISSUE TITLE
[Bug] Items not being force inserted by hopper when drawer has void upgrade

### ISSUE THREAD

**Issue by jarquafelmu** [Buuz135/FunctionalStorage#27]
# Versions
Minecraft: v1.18.1
Forge: v39.1.2
Functional Storage: v0.0.10

# Issue

## What is Happening
I have two drawers set up with void upgrades so that my farm doesn't overflow, and excess items just get deleted. However, this is not happening. I can force insert items manually, but that wasn't what I wanted to do.

## What I Expected to Happen
The hopper to force push the items into the drawer, even though it would void them.

![image](https://user-images.githubusercontent.com/5807272/162657140-618814fd-8c1a-466c-b7fb-e7d66136f111.png)
![image](https://user-images.githubusercontent.com/5807272/162657330-815a6320-3b34-4ae4-9af3-93e4d234843e.png)
![image](https://user-images.githubusercontent.com/5807272/162657349-db5349b4-938b-46f6-b386-befcc0e32613.png)
![image](https://user-images.githubusercontent.com/5807272/162657497-041ef74d-678d-47cb-8027-d778e25106f1.png)
![image](https://user-images.githubusercontent.com/5807272/162657521-ca5d20d2-4fba-4069-a1ca-6e0c8de98eb4.png)

**Comment by jarquafelmu** [comment]
Of course, since I complained about it, it is working now....

**Comment by jarquafelmu** [comment]
Okay, this is not actually all in my head. It seems to happen if I go offline, when I come back my hopper feeding into the storage controller is full and isn't inserting. Once I take the stuff out and manually put it into the drawers, the hoppers insert normally again.

**Comment by Buuz135** [comment]
Can you try with the latest version?

**Comment by jarquafelmu** [comment]
I will have to wait until our modpack can update to 1.18.2

**Comment by Nitaeram** [comment]
In version functionalstorage-1.18.2-0.0.15.jar using hopper works only on controller and modded pipes don't work

**Comment by stillie** [comment]
@Nitaeram What pipes must we using then? Vanilla doesnt exactly have pipes?

Im having the same issue with version 0.0.5 (1.18)

**Comment by Nitaeram** [comment]
@stillie vanilla hoppers work

**Comment by stillie** [comment]
So just to confirm, i need to use Modded pipes -> Vanilla Hopper -> Drawer? :/ 

Is the dev planning on looking into this?

**Comment by Nitaeram** [comment]
Yes thats what you need to do

**Comment by Buuz135** [comment]
Just as a heads up, some mods check if the inventory is full before sending items which is good and bad at the same time, and I need to work around it to make them believe it can hold more.
