### ISSUE TITLE
[1.20.1] locked fluid drawer with 0mb liquid will not function correctly in the drawer network

### ISSUE THREAD

**Issue by Thjingdian** [Buuz135/FunctionalStorage#275]
When the amount of locked fluid drawer is 0mb, there is a high probability that it will not be input correctly through the controller. The fluid remains in place, but if the target is mined and repositioned there is a chance that a small portion of the 0mb locked fluid drawer will work properly.

**Comment by Buuz135** [comment]
I can't replicate this
