### ISSUE TITLE
[1.20.1] Drawers don't connect to Cooking For Blockheads multiblock

### ISSUE THREAD

**Issue by jimmylobo2** [Buuz135/FunctionalStorage#287]
**Functional Storage Version:1.20.1-1.2.11**

**Titanium Version: 3.8.28**

**Crashlog If Applicable (Upload to pastebin/gist):**

Using either a standalone drawer next to the kitchen or through a controller doesn't seem to work. Items are not taken into account in the kitchen - putting them into CFB container (counter, fridge, etc.) is required.

Modpack: All The Mods 9-0.2.60
Functional Storage version: 1.20.1-1.2.11
Cooking For Blockheads version: 16.0.4
Forge: 47.2.20

**Comment by Buuz135** [comment]
Thats not a feature of the mod

**Comment by eeeBs** [comment]
Can it be? It used to be a function of the original Storage Drawer mod. It was useful for cooking and magic mods that could read a nearby container. It's missed.
