### ISSUE TITLE
[1.20.1] Unable to get fluids out of a Fluid Drawer using a Bucket

### ISSUE THREAD

**Issue by Svish** [Buuz135/FunctionalStorage#292]
Playing ATM9 - To The Sky, and found the very useful Fluid Drawers, but when using a bucket, they seem one-way, which seems wrong? I.e. using a bucket I'm only able to put fluids _into_ a Fluid Drawer, not pull anything back out of them.

I have to use a workaround, with a pusher upgrade into a barrel, which I am then able to pick the fluid up from with a bucket, but... seems a bit silly. Should probably be possible to simply right-click a Fluid Drawer with an empty bucket, to fill the bucket with whatever fluid is in the drawer?

**Functional Storage Version:** `functionalstorage-1.20.1-1.2.11.jar`

**Comment by Buuz135** [comment]
@Svish

**Comment by Svish** [comment]
> Have you tried left clicking with a bucket?

🤦‍♂️

That does indeed work! I've only tried to right click, as that's how I get fluids out of everything else, like water/lava sources, barrels, and so on. Didn't even think to try left click, but when I think about it I guess it makes sense since that's how you get items out of regular drawers too.

Thank you for the reply and sorry for wasting time 🙈👍

**Comment by Eydamos** [comment]
Not being able to interact "normally" with an empty bucket has driven me crazy. I'm just here to create a bug report until I found this thread. Never would I ever have had the idea to left click the fluid drawer. As probably more people have this problem maybe it would be a good idea to document this on the curseforge page and wherever else you host downloads for the mod.
