### ISSUE TITLE
[1.21] Oak drawer recipes incorrect

### ISSUE THREAD

**Issue by Kevin-Marsh** [Buuz135/FunctionalStorage#293]
The oak drawer recipes in 1.21 seem to be incorrect. The recipes used are the old alternate recipes which means that you can't craft oak drawers with oak planks but have to use a workaround like chiselling the planks to get access to the oak variant. This applies to all oak variants.

1.21 which matches oak alternate
https://github.com/Buuz135/FunctionalStorage/blob/1.21/src/generated/resources/data/functionalstorage/recipe/oak_1.json
1.19 oak alternate
https://github.com/Buuz135/FunctionalStorage/blob/1.19/src/generated/resources/data/functionalstorage/recipes/oak_drawer_alternate_x1.json
1.19 oak drawer which allows you to make it with planks
https://github.com/Buuz135/FunctionalStorage/blob/1.19/src/generated/resources/data/functionalstorage/recipes/oak_1.json

**Comment by Matyrobbrt** [comment]
I am unable to reproduce it with just Functional Storage. Do you have other mods installed?
