### ISSUE TITLE
[1.21] Custom Compacting recipes not working in 1.21

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#302]
**Functional Storage Version:** 1.3.1

**Titanium Version:** 4.0.12

I recall that version 1.20.1 there was an option to add custom compacting recipes via datapacks. 
I am checking in 1.21 and they are no longer working. 
I even tried to change the path of the folders and rename things to match the path structure of the mod.jar 

I am mostly trying to add a clay balls to Clay block and a Snow balls to snow block recipe.

**Comment by Matyrobbrt** [comment]
Are your recipes under `recipe` (singular) and not `recipes` (plural)? Multiple directories were changed by Mojang from plural to singular in 1.21, recipes are one of them.

**Comment by Matyrobbrt** [comment]
I'm still unable to reproduce it, please share your data pack.

**Comment by ffuentesm** [comment]
This is the last iteration that I made, might be wrong from what is required thought. 
[functionalstorage.zip](https://github.com/user-attachments/files/16499594/functionalstorage.zip)

**Comment by Buuz135** [comment]
You are using "item" in the recipe when it should be "id"
