### ISSUE TITLE
[1.20.1] Items inside of drawer appearing in other blocks info

### ISSUE THREAD

**Issue by FinlaySS** [Buuz135/FunctionalStorage#307]
![sigmaenigma](https://github.com/user-attachments/assets/17a86485-d69e-4552-acf0-11647a5a89fd)
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**
1.20.1-1.2.11
**Titanium Version:**
1.20.1-3.8.27
**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
I dont add support for JADE so its probably not my fault
