### ISSUE TITLE
Make nether quartz turn into block of quartz in compacting drawer

### ISSUE THREAD

**Issue by wilsonw13** [Buuz135/FunctionalStorage#31]
In the original mod, this worked in a compacting drawer but doesn't work here. Is this a bug?  Glowstone Dust <==> Glowstone works as intended.

**Comment by a1qs** [comment]
you can manually do this using the "functionalstorage:ignore_crafting_check" tag manually and adding it to both items if you'd like it, currently it doesnt seem possible by default
