### ISSUE TITLE
[1.21] Framed Compacting Drawer textures gone

### ISSUE THREAD

**Issue by EmmaRavens** [Buuz135/FunctionalStorage#311]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:** 1.21.0-1.3.2

**Titanium Version:** 4.0.12

**Crashlog If Applicable (Upload to pastebin/gist):**

After teleporting to another dimension returned to my base to find the texture gone

![image](https://github.com/user-attachments/assets/eca37573-34c1-4d27-9347-bdc561979b7b)

**Comment by Buuz135** [comment]
Does breaking them and placing them again fixes it?

**Comment by EmmaRavens** [comment]
Yes it does, by breaking 1 drawer, all the others connected to it will fix aswell
If I go to another dimension and back to the base will also fix it.

**Comment by EmmaRavens** [comment]
ah right, I have a chunk loader in the chunk where the drawers are, not sure if that will make any different but though I should mention it

**Comment by EmmaRavens** [comment]
yep, not sure if it is happening now though, been a while since I used them

**Comment by Buuz135** [comment]
Will close this, and reopen in case it happens again
