### ISSUE TITLE
[1.20.1] Game frozen for few seconds when linking/unlinking a drawer to a controller

### ISSUE THREAD

**Issue by SeaLoong** [Buuz135/FunctionalStorage#314]
**Functional Storage Version:** 1.20.1-1.2.10

**Titanium Version:** 3.8.32

I want to link a new drawer to my controller which has been connected with **hundreds of drawers**. But game is froze for a few seconds each time I try do it. And it only happen on **client-side**, the **server-side** is normal. (I mean, not cause server tps down rapidly.)

There is spark profiler report snapshot.
![20240830-193542](https://github.com/user-attachments/assets/d60282b6-e784-4cc0-98ba-db394c3d24fc)

I see the source code, `rebuildShapes` cost too much time, can you optimize it? or is there other solution?
[rebuildShapes method in source code](https://github.com/Buuz135/FunctionalStorage/blob/e3f1b16ecb6e9487188f2308fd3aa563b3a6273d/src/main/java/com/buuz135/functionalstorage/util/ConnectedDrawers.java#L84)

Also, I find the same situation when a LinkingTool in my hand for a while.
[the reason in source code](https://github.com/Buuz135/FunctionalStorage/blob/e3f1b16ecb6e9487188f2308fd3aa563b3a6273d/src/main/java/com/buuz135/functionalstorage/client/ControllerRenderer.java#L90)

**Comment by Buuz135** [comment]
Define "hundreds" 
![HmmSuspectGIF](https://github.com/user-attachments/assets/e65bb460-8726-4bda-aa1e-9a0dc3112910)

**Comment by SeaLoong** [comment]
@Buuz135 
![2024-08-30_20 06 05](https://github.com/user-attachments/assets/cf61070c-69dd-4b6f-b0a9-6926df9157e7)

About 200-300 drawers? I guess.
