### ISSUE TITLE
[FEATURE REQUEST] Add Compatibility with Vanilla Crafters.

### ISSUE THREAD

**Issue by ArtpokeBr** [Buuz135/FunctionalStorage#315]
Currently if you place a Vanilla Crafter aiming at a Drawer, Items will be spitted on the floor.

- My Suggestion is to make Drawers Accept Items directly from Vanilla Crafters, just like Chests do. =)

![image](https://github.com/user-attachments/assets/f0562710-69ee-4683-8c2b-d91e6542b197)

**Comment by ArtpokeBr** [comment]
Good to also point out that upon testing with a Collector Upgrade, Sometimes it is able to collect, sometimes it doesn't.

**Comment by Buuz135** [comment]
I think thats a vanilla problem

**Comment by Buuz135** [comment]
Fixed in https://github.com/neoforged/NeoForge/pull/1506

**Comment by ArtpokeBr** [comment]
Oh nice! thx Buuz :)

**Comment by Buuz135** [comment]
Fixed in Neoforge
