### ISSUE TITLE
[1.21] Client crash when crafting 2x2 Framed Drawers

### ISSUE THREAD

**Issue by ExaltedZoro** [Buuz135/FunctionalStorage#322]
Attempting to craft 2x2 Framed Drawers crashes the client when it tries to copy the drawer contents over.

Functional Storage Version: 1.21.1-1.3.3

Titanium Version: 1.12-4.0.21

Crashlog: https://pastebin.com/rhYFWFkc

**Comment by GaeaKat** [comment]
It seems it crashes because of Fast Workbench, though without, it just prints the exceptionto console and the recipe fails to work. Hopefully my PR fixes this issue!
