### ISSUE TITLE
Lighting on the face of Drawers

### ISSUE THREAD

**Issue by WastelandOasis** [Buuz135/FunctionalStorage#33]
The drawers lighting seems to be messed up on the face and when they are next to blocks it will look almost like a shadow is cast over it.  Version 0.0.14 on 1.18.2

**Comment by Buuz135** [comment]
Enable experimentalLightning on the forge client config file

**Comment by rckymtnrfc** [comment]
It also seems to persist after making the change if Rubidium is installed.  FYI

**Comment by invalidtask** [comment]
Issue still present with the latest version in All The Mods 7 modpack. Experimental lighting flag mostly fixes it but breaks other models for other mods.

**Comment by BrewingCoder** [comment]
if you're referring to "experimentalForgeLightPipelineEnabled" then it is already enabled in the FTB Skies Modpack.

**Comment by Chezzik** [comment]
I've added this to minecraft/config/forge-client.toml, but the file is overwritten the next time I start the game.

Is there some secret for making my changes stick?
