### ISSUE TITLE
mass drawer addition to controller

### ISSUE THREAD

**Issue by Uvbnstrk2** [Buuz135/FunctionalStorage#335]
writing this while manually adding 20480 drawers to my system, would love a better way to mass add them

**Comment by Uvbnstrk2** [comment]
would like to alse mention that after exactly 256 drawers are on a controller adding/removing from that controller causes massive lag spikes

**Comment by Buuz135** [comment]
The linking tool has a multiple mode, the description should tell you how to change it …
