### ISSUE TITLE
Storage controller unable to insert into compacting drawer that does not already have one of the item in it

### ISSUE THREAD

**Issue by WebDragon** [Buuz135/FunctionalStorage#34]
I have a storage controller connected to a locked compacting drawer with iron blocks/ingots/nuggets in it (totals show 2 blocks, 21 ingots, 195 nuggets)

If I take one iron block out, click it into the face of the controller, it gets inserted no problem
If I take out both iron blocks (leaving 3 ingots/33 nuggets) and attempt to click the stack of 2 iron blocks into the controller, it refuses to insert them into the system's compacting drawer. 

ouch.

Modpack: Direwolf20 1.18.2
Forge version: (from F3) 1.18.2-forge-40.1.19
Functional Storage version: functionalstorage-1.18.2-0.0.14.jar

**Comment by Jared87** [comment]
Its not only a compacting drawer problem.
As soon a drawer of any kind is locked an has 0 items in it the controller seems to loose the knowledge of having a place for this item.

Place a drawer and a controller, add any item and lock the drawer. Remove all items and try to rightclick them onto the controller => nothing happens. Add one item to the drawer and rightklick the controller => items get added.

In the compacting drawer case:
If you have 8 nuggets in the drawer and an ingot in the bags nothing happens on controller rightclick, if you have an ingot and an nugget in your bag and doubleclick the controller both get added.
