### ISSUE TITLE
[Request] Allow insert into a non-empty drawer with non-matching item in hand

### ISSUE THREAD

**Issue by lpacphantom** [Buuz135/FunctionalStorage#36]
Currently, you can only insert into a drawer with items in it if you have that item in your main hand and right click or if you double right click with an empty hand to push all of that item in your inventory. Storage Drawers was much more forgiving about how to trigger inserts and it's really confusing when old habits don't do what you're expecting.

**Comment by Buuz135** [comment]
What version are you using?

**Comment by lpacphantom** [comment]
1.18.2-0.0.15
