### ISSUE TITLE
[Bug] Controller doesn't prioritize drawers with items when inserting.

### ISSUE THREAD

**Issue by lpacphantom** [Buuz135/FunctionalStorage#37]
If you have a large array of drawers connected to a controller, some empty and some with items, when you import items that already have a drawer the controller will not necessarily put the items there. I think the empty drawers are being found by whatever algorithm is trying to find a spot and the controller just accepts that and moves on.

I'm finding this from a Mekanism Digital Miner pushing ores into a controller. Sometimes an ore that already has a drawer will be put into an empty one despite having plenty of room in the other drawer. I can't lock all the drawers because the miner is pulling anything with the ore tag, so there's still things I don't have yet.

**Comment by Buuz135** [comment]
What version are you using?

**Comment by lpacphantom** [comment]
1.18.2-0.0.15

**Comment by Buuz135** [comment]
I recommend you to lock the drawers as I can't internally safely modify the inserting behaviour of external mods.
