### ISSUE TITLE
Can't export from refined storage using controller into linked draw with item already set

### ISSUE THREAD

**Issue by sprocketaudio** [Buuz135/FunctionalStorage#40]
As per the title, I have a controller, with a linked drawer using linking tool. I have refined storage setup and an export bus connectred to the bottom of the controller and have 64 of an item in the drawer. I have 500+ of item in the refined storage network.

Expected results::

The item should export out of the refined storage network into the drawer through the controller.

**Comment by Buuz135** [comment]
What version are you using?

**Comment by sprocketaudio** [comment]
Thanks for reply.

Version functionalstorage-1.18.2-0.0.15.jar in the ATM7 pack (newest version of pack).

**Comment by Buuz135** [comment]
Can you show me a picture of your setup?

**Comment by sprocketaudio** [comment]
Sorry this was be forgetting to add items to export filter.. closed
