### ISSUE TITLE
[Bug] Storage Controller

### ISSUE THREAD

**Issue by GangstaPichu** [Buuz135/FunctionalStorage#43]
Seems if one storage controller gets in the line of another, it crashes the game when you try and put something in for it to sort. It'll only happen after adding everything. I thought I'd try and chain them for item sorting for how I have stuff in just long rows cause of all the items in this mod pack I'm using. I ended up finding out that doesn't work along with crashing my game and the server this modpack is on. 

Version: 1.18.2

Modpack: Valhesia Volatile

**Comment by Buuz135** [comment]
What mod version are you using in that pack?

**Comment by GangstaPichu** [comment]
> What mod version are you using in that pack?
functionalstorage-1.18.2-0.0.14

**Comment by Buuz135** [comment]
Can you check if it happens in functionalstorage-1.18.2-0.0.15 ? I can't link a controller to another controller
