### ISSUE TITLE
Prioritize drawers that already have an item over empty ones

### ISSUE THREAD

**Issue by frquadrat** [Buuz135/FunctionalStorage#45]
Cool approach, the Function Storage system!

Something that bothers me...

### setup
Modpack "FTB Direwolf20 1.8" version 1.4.1, client/server setup.
versions
functionalstorage-1.18.2-0.0.17
forge 4.1.47
rftoolsbuilder-1.18-4.0.12

I have a Function Storage system with a controller linked to a bunch of drawers. The controller is placed upon an RFToolsBuilder builder (configured as a quarry) so that the builder puts its stuff into the drawers.
Most drawers are locked, some with upgrades, some with void upgrade.
Some drawers are empty in case there are items that I didn't expect.

### experiencend behaviour
In the case that an unwanted item gets in, when I remove those items from the drawer, the next random stuff that gets into the Function Storage system is placed into that drawer, even if there is already another drawer with those items that still has enough capacity.

Example: One drawer empty, one with iron ore (locked), some dirt gets in, is placed into the empty drawer, I make sure no dirt gets in anymore, I remove it the dirt (drawer is empty), next iron ore is being put into that drawer.

### expected behaviour
Drawers in the same system that already have the incoming item must always be preferred over an empty one as long as they have the capacity or a void upgrade.

If I can provide more information, let me know.
Thanks 
FR²

**Comment by Buuz135** [comment]
I can't change how items are inserted safely the mod that inserts selects where it goes #37

**Comment by JustJinxed** [comment]
I'm experiencing this even when using pipes to pull items from a chest, into the storage controller. 
Considering Storage Drawers can and does seem to manage this safely, are you certain this expected behavior? I'm confused how a secondary mod has control over this?
