### ISSUE TITLE
New Feature idea

### ISSUE THREAD

**Issue by castilio20** [Buuz135/FunctionalStorage#48]
![2022-06-13_22 56 57](https://user-images.githubusercontent.com/76228548/173436540-cb5e1e96-e364-4c03-8374-834eac6f0156.png)
Right now it doesnt show anything the new feature would be to show the name or somthing so you know what you have in the drawer when you have in inventory

**Comment by posicat** [comment]
This would be especially useful for mods that add lots of ores, and ingots, it's often hard to tell between them just be look, a title on the box showing what's in them would be handy.  Even if it's only when you hold shift or something like that.
