### ISSUE TITLE
Drawers facing east or west render with darkened front face

### ISSUE THREAD

**Issue by Canada-LaVearn** [Buuz135/FunctionalStorage#5]
![2022-01-05_17 01 51](https://user-images.githubusercontent.com/80727688/148295937-d25e8298-b992-471a-b365-d04cde26143b.png)
As the image shows, drawers facing north or south render fine, but facing east or west causes them to have darkened faces.

**Comment by Buuz135** [comment]
Enable experimental lightning in the forge client config
