### ISSUE TITLE
Crash when adjusting drawers connected to Refined Storage

### ISSUE THREAD

**Issue by ciserman** [Buuz135/FunctionalStorage#52]
[crash-2022-07-07_13.57.24-server.txt](https://github.com/Buuz135/FunctionalStorage/files/9066264/crash-2022-07-07_13.57.24-server.txt)
Drawer Controller is connected to a Refined Storage network with an External Storage attachment. Many items are missing from the drawer network and some of them show double the amount they should. While trying to check my Functional Storage network and using the Linking Tool my game will crash and requires me to restore from a backup to get back into the game.

**Comment by Buuz135** [comment]
Do you have multiple FS controllers connected to each other?
