### ISSUE TITLE
Crash when applying void upgrade to compacting drawer

### ISSUE THREAD

**Issue by sdlopez** [Buuz135/FunctionalStorage#61]
[crash-2022-07-28_08.21.34-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9206019/crash-2022-07-28_08.21.34-client.txt)

When trying to apply a void upgrade to a compacting drawer, the game crashes. (Previously the compacting drawer had 3 gold upgrade also)

**Comment by James103** [comment]
Another player reported a similar crash in https://github.com/AllTheMods/ATM-7/issues/1277, but, according to the reporter, the crash occurred while trying to remove a void upgrade from a drawer that had two void upgrades in its upgrade slots.
[crash-2022-07-27_23.11.41-client.txt](https://github.com/AllTheMods/ATM-7/files/9205307/crash-2022-07-27_23.11.41-client.txt)
