### ISSUE TITLE
The Game crash after taking out copper upgrade. (linked with controller)

### ISSUE THREAD

**Issue by UnKinSeong** [Buuz135/FunctionalStorage#63]
As the title mention. The game Crash as soon as the copper upgrade taking out.
If the drawer linked with controller. the upgrade can't be removed. 
Game crashed after attempted to take out the upgrade.
[crash-2022-07-31_14.24.24-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9228174/crash-2022-07-31_14.24.24-client.txt)
.

**Comment by UnKinSeong** [comment]
By the way. The drawer is connected to the controller and linked to the refined storage via storage port.

**Comment by Buuz135** [comment]
Update the mod
