### ISSUE TITLE
Adding a gold upgrade to Functional Storage drawers causes a hard client crash #1305

### ISSUE THREAD

**Issue by crysallis** [Buuz135/FunctionalStorage#65]
I have a compacting drawer that had 2 copper upgrades on it, I decided to upgrade that to gold. I crafted the upgrade and right clicked it on the drawer and my client hard crashed. (see crash report 1.36.45) then once I reloaded the client I opened the drawer to remove one of the upgrades and my client hard crashed again (see crash report 1.41.45). I've added and removed many of the copper upgrades, but this was the first gold upgrade. The qty in the drawer is 17.3 and the double copper has a max of 32k. So adding the gold shouldn't been an issue, nor would removing a copper after the gold was applied.
[crash-2022-08-02_01.36.45-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9239598/crash-2022-08-02_01.36.45-client.txt)
[crash-2022-08-02_01.41.45-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9239599/crash-2022-08-02_01.41.45-client.txt)
ATM 0.4.23

**Comment by Buuz135** [comment]
Try updating to 0.0.20
