### ISSUE TITLE
[Bug] Crash to desktop when using mouse to add or remove upgrades from compacting drawers

### ISSUE THREAD

**Issue by PutNameHere42** [Buuz135/FunctionalStorage#67]
**Modpack**

FTB Direwolf20 1.18

**Modpack version**

1.8.0

**Log Files**

Here: [crash-2022-08-05_15.48.52-client.txt](https://github.com/Buuz135/FunctionalStorage/files/9269295/crash-2022-08-05_15.48.52-client.txt)

**Describe the bug**

As described in the title, the game freezes and crashes when the mouse is used to add or remove upgrades from compacting drawers. This happens regardless weather the drawer has items or not, it connected via pipes etc, or is linked to a controller. Using Shift+Click does not trigger the issue, but there's no way to remove said upgrades from existing drawers.

**Steps to reproduce**

1. Place compacting drawer
2. Open upgrades inventory
3. Pick up an upgrade with the mouse cursor and click it into an empty slot. Immediate crash.
4. Also applicable with existing upgraded drawers. Simply mouse over an installed upgrade, click, immediate crash.

**Expected behavior**

No crash

**Additional info**

The crash seems to revert some amount of player progress, but not block progress. For example, after reloading the world, the player position was reverted to 5~ minutes prior, but blocks placed during that time were not reverted. May be unrelated.

*Also posted to FTB issue tracker

**Comment by Buuz135** [comment]
Update the mod
