### ISSUE TITLE
Crashes when linking and unlinking drawers

### ISSUE THREAD

**Issue by iRedPandaz** [Buuz135/FunctionalStorage#68]
I have a Applied Energistics storage bus attached to the controller and sometimes it stops reading from certain drawers so when unlinking them to relink them in hopes of this fixing it the server crashes. This happens even without the Storage Bus attached.
I have attached a copy of the crash report.

[crash-2022-08-06_15.50.50-server.txt](https://github.com/Buuz135/FunctionalStorage/files/9275259/crash-2022-08-06_15.50.50-server.txt)
.

**Comment by Buuz135** [comment]
[Closed ](https://github.com/Buuz135/FunctionalStorage/commit/df75dfa8f08c6b13176ad9574f4cad4e06d23956)
