### ISSUE TITLE
Add an upgrade to allow items to be sorted into the network.

### ISSUE THREAD

**Issue by posicat** [Buuz135/FunctionalStorage#72]
Am I missing an option for what was in previous mods the "slave controller" or a secondary input into the system.  Right now I'm having to pipe a lot of inputs into the hopper like mine cart unloading, automatic furnaces, and various other devices that output objects.

It would be really handy to just add a mod to a drawer that allows any items placed into it to be sorted into their respective drawer like putting them in the storage controller.

**Comment by Buuz135** [comment]
Added in latest version
