### ISSUE TITLE
Removing a locked drawer's void upgrade voids any items pushed into the linked controller

### ISSUE THREAD

**Issue by koolboat** [Buuz135/FunctionalStorage#73]
Pushing items into a storage controller which had a linked locked drawer's void upgrade removed will void any items that were pushed into it.

Occurs on 1.0.3

Repro video:
https://user-images.githubusercontent.com/61613274/185512192-93b3f818-1c29-4566-a9a7-a5faf2356ebb.mp4

**Comment by Buuz135** [comment]
Thanks a lot for the video
