### ISSUE TITLE
Very bad performance with insertions

### ISSUE THREAD

**Issue by cha0s** [Buuz135/FunctionalStorage#75]
Hello!

I have a drawer network of about 550~ drawers.

I like to attach an ME storage bus to the drawers because it's simple and I've done it since the days of Agrarian Skies :)

When I do this, however, tps on the server plummets.

The vast majority of time spent seems to be in `com.buuz135.functionalstorage.block.tile.ControllableDrawerTile.isVoid ()`.

![Screenshot from 2022-08-20 14-09-45](https://user-images.githubusercontent.com/298123/185762752-6cdfce86-14cd-4262-8427-a61b8d7cbb65.png)

![Screenshot from 2022-08-20 14-11-35](https://user-images.githubusercontent.com/298123/185762792-621c845f-f8a3-41b8-b684-a7540e0e1452.png)

I'm not sure if there's more information I can provide that would be useful. If so, let me know! I would really love to keep your using drawers but they absolutely destroy performance.

**Comment by Buuz135** [comment]
Which mod version are you using?

**Comment by cha0s** [comment]
1.0.2, running the latest update on All the Mods 7

**Comment by cha0s** [comment]
I'm not much into Java, but I am a coder.

It seems like the `getItem()` method of the ItemStack is pretty expensive, and `isVoid` is doing this:

```
        for (int i = 0; i < this.utilityUpgrades.getSlots(); i++) {
            if (this.utilityUpgrades.getStackInSlot(i).getItem().equals(FunctionalStorage.VOID_UPGRADE.get())) {
                return true;
            }
        }
```

every tick(?). Perhaps it would be worth caching the result of that call and only updating it when an upgrade is inserted/removed

**Comment by cha0s** [comment]
I renamed the issue because I'm pretty sure it's a general problem with insertions rather than anything to do with ME storage buses in particular.

**Comment by cha0s** [comment]
Moving to https://github.com/Buuz135/FunctionalStorage/pull/81
