### ISSUE TITLE
Drawer / Controller / Linking Issue

### ISSUE THREAD

**Issue by MrSataana** [Buuz135/FunctionalStorage#78]
I’m the ATM7 ttS pack, it randomly seems to unlink drawers.
I am using a controller that is fed by a Pipez item pipe, on occasion it stops putting in item(s).
The linking tool shows as linked, but when I then click the drawer again in link mode, it seems that items go in again.
No idea if this is due to the Void bug where it just stops putting items in or not, but it makes the system very unreliable.

**Comment by Buuz135** [comment]
What version of the mod are you using?

**Comment by MrSataana** [comment]
> What version of the mod are you using?

functionalstorage-1.18.2-1.0.4

**Comment by Buuz135** [comment]
I think this should be fixed
