### ISSUE TITLE
Duplication bug with FTB Ultimine

### ISSUE THREAD

**Issue by TinyPandas** [Buuz135/FunctionalStorage#84]
Current Pack: ATM 7
Version: 0.4.25

FunctionalStorage Version: 1.18.2-0.0.20
FTB Ultimine Version: 1802.3.3-build.55
Forge Version: 40.1.68

When vein mining drawers attached to a controller, the controller retains it's contents prior to the drawers being broken.

Contents in Controller
![image](https://user-images.githubusercontent.com/10274646/186788104-128605d7-c4f1-440b-b9b4-dcaf2c8571fb.png)

Drawers are still "ghosted"
![image](https://user-images.githubusercontent.com/10274646/186788119-19b6e68c-bcc1-4098-80ca-5d5c356e81a1.png)

**Comment by TinyPandas** [comment]
Upon further testing, it seems this is irrelevant to Ultimine, and retains the contents even if manually broken.

**Comment by Buuz135** [comment]
Can you see if it happens raplacing everything in FS version 1.0.5 ?

**Comment by TinyPandas** [comment]
It seems the pack updated, and is using 1.0.5. I was unable to reproduce! Thank you!

**Comment by TinyPandas** [comment]
It does seem to be reoccurring in 1.0.5 again. This time without the use of Ultimine.
