### ISSUE TITLE
[1.19.2] Can access the drawer UI from the front of the block

### ISSUE THREAD

**Issue by ffuentesm** [Buuz135/FunctionalStorage#88]
Mod version: 1.19.2-1.0.6
Forge: 43.1.16

When I try to access the drawer UI to add or remove upgrades, it does not work if I try to access it from the front of the block. I need to click on the sides of the block to have it work.
This is a problem due to having to break the black from the wall of drawers if I need to access the UI.

Also, could you add a "click with an upgrade to add it" so that it is fast if I just want to expand the drawer storage without opening the UI?

**Comment by Buuz135** [comment]
Right click on the border of the block on front side, there are different bounding boxes to guide you

**Comment by Rasdevaysa** [comment]
1.19.2 Same problem, spammed right click on every pixel and nothing

**Comment by Buuz135** [comment]
Do you have titanium updated?

**Comment by Rasdevaysa** [comment]
Yes, you're right, that was the problem. Thanks for mod by the way
