### ISSUE TITLE
Compacting Ice

### ISSUE THREAD

**Issue by qn-T** [Buuz135/FunctionalStorage#91]
Ice does not compact to Packed / Blue ice in a compacting drawer.

Mod Pack: ATM7:TTS.
No Additional mods.

**Comment by andrewsf** [comment]
It is not compaction, it is just one-way crafting. 
You cannot turn blue ice into packed ice, and you cannot turn packed ice into ice.

**Comment by ffuentesm** [comment]
> Ice does not compact to Packed / Blue ice in a compacting drawer.
> 
> Mod Pack: ATM7:TTS. No Additional mods.

https://vanillatweaks.net/picker/crafting-tweaks/
If you add the Unpackable Ice data pack, it will work.

**Comment by Buuz135** [comment]
You can add `functionalstorage:ignore_crafting_check` for stuff that doesn't have an uncrafting recipe and it will work in the drawer, glowstone and clay already has this but I will add it to the ice too
