### ISSUE TITLE
[Bug] [1.18.2-1.0.6] - Armory not linking to Storage Controller

### ISSUE THREAD

**Issue by Emeraude998** [Buuz135/FunctionalStorage#98]
I'm playing ATM7 and trying to link an Armory Cabinet to my Storage Controller using the linking tool but when I right click it on the block (whatever face I use), it just switches the linking tool from adding to removing mode.

I tried the linking tool on other drawers and it works perfectly fine.

**Comment by Buuz135** [comment]
Intended
