### ISSUE TITLE
Compacting Drawers Voiding Items

### ISSUE THREAD

**Issue by ZaksterNZ** [Buuz135/FunctionalStorage#99]
Not sure if intended, compacting drawers will void items if broken with the wrong tool. Pretty pricey mistake to make.

functionalstorage-1.18.2-1.0.6
Forge: 40.1.80

**Comment by andrewsf** [comment]
Bugs get fixed over time and introduced over time. You haven't listed basic information like the mod version or your modpack & its version (perhaps a full list of your mods).

**Comment by ZaksterNZ** [comment]
That was silly of me, sorry. Any drawer, other than the framed/compacting drawer wont void itself when broken with wrong tool. I was more just curious if this is intended, as it takes a long time to break when not using the right tool.  Updated original post with version numbers.

**Comment by Buuz135** [comment]
Nothing I can do about it as the tool is a pickaxe and all minables by a pick dont drop stuff if not mine with one.
